### ISSUE TITLE
README needs to be better

### ISSUE THREAD

**Issue by notenociz** [mrzmyr/head-generator#1]
Could we getter a more extensive README pls? I like this idea and feel that it will be useful for me. How do I use it?

NOTE: I'm not asking you to go out of your schedule to do this. After all, this seems like a non-work thing and it's fully up to you to move it forward or keep it as is.

**Comment by mrzmyr** [comment]
Thanks for the motivation :), as you can see, I worked on it 3 years ago. I'm probably looking into it soon and update it a bit more. 

In the meanwhile you can check out the current version here: http://mrzmyr.github.io/head-generator

**Comment by notenociz** [comment]
I've added the link to pull request #2

**Comment by mrzmyr** [comment]
thanks for that. :)
