### ISSUE TITLE
Viewport meta tag's content is wrong

### ISSUE THREAD

**Issue by notenociz** [mrzmyr/head-generator#3]
Currently, it compiles to `<meta name="viewport" content="viewport-width=device-width, viewport-initial-scale=1, viewport-minimum-scale=1">` with default values. However, this should be `<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">` to work properly and fix a few sizing issues.

I've been meaning to issue this for a while and only now got a chance. I'm a bit scared to go into the code so hopefully, you can fix it quickly to solve further issues.

**Comment by mrzmyr** [comment]
0efc11d9b7567daec993769510318b76e62c0cae, there you go :shipit:.

**Comment by notenociz** [comment]
Thanks for that.
